# Generated by Django 2.0.5 on 2018-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
