# Generated by Django 2.0.6 on 2018-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='歌曲名')),
            ],
            options={
                'verbose_name': '影乐',
                'verbose_name_plural': '影乐',
            },
        ),
    ]
