# Generated by Django 2.0.5 on 2018-06-23 17:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuaXuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
            ],
            options={
                'verbose_name': '幕后花絮',
                'verbose_name_plural': '幕后花絮',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(default='', max_length=255, unique=True, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='YingPingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=255, verbose_name='作者')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞数')),
                ('laiyuan', models.CharField(default='', max_length=255, verbose_name='来源')),
            ],
            options={
                'verbose_name': '影评',
                'verbose_name_plural': '影评',
            },
        ),
        migrations.CreateModel(
            name='YingXunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('laiyuan', models.CharField(default='', max_length=255, verbose_name='来源')),
            ],
            options={
                'verbose_name': '影讯',
                'verbose_name_plural': '影讯',
            },
        ),
    ]
