# Generated by Django 2.0.5 on 2018-06-19 22:49

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180618_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuaXuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '幕后花絮',
                'verbose_name_plural': '幕后花絮',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=255, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='YingXunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('laiyuan', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源')),
            ],
            options={
                'verbose_name': '影讯',
                'verbose_name_plural': '影讯',
            },
        ),
    ]
