# Generated by Django 2.0.6 on 2018-06-25 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='类型')),
            ],
            options={
                'verbose_name': '人物类型',
                'verbose_name_plural': '人物类型',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('jianjie', models.TextField(default='', max_length=255, verbose_name='简介')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='生日')),
                ('fengmian', models.ImageField(default='', upload_to='image/%Y/%m/%d', verbose_name='封面')),
                ('category', models.CharField(default='', max_length=255, verbose_name='人物类型')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('xuexing', models.CharField(default='', max_length=255, verbose_name='血型')),
                ('xingzuo', models.CharField(default='', max_length=255, verbose_name='星座')),
                ('zhiye', models.CharField(default='', max_length=255, verbose_name='职业')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
    ]
