# Generated by Django 2.0.5 on 2018-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fengmian',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
