# Generated by Django 2.0.5 on 2018-06-18 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180618_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='info',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='fengmian',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='info',
            name='jianjie',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='简介'),
        ),
    ]
