# Generated by Django 2.0.5 on 2018-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20180618_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='xingzuo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='星座'),
        ),
        migrations.AddField(
            model_name='info',
            name='xuexing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='血型'),
        ),
        migrations.AddField(
            model_name='info',
            name='zhiye',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='职业'),
        ),
    ]
