# Generated by Django 2.0.6 on 2018-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='网站名')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='LunBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
