# Generated by Django 2.0.5 on 2018-06-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbo',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='链接'),
        ),
    ]
