# Generated by Django 2.0.5 on 2018-06-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180618_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='img',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
