# Generated by Django 2.0.5 on 2018-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='url',
            field=models.CharField(max_length=255, verbose_name='链接'),
        ),
    ]
