# Generated by Django 2.0.5 on 2018-07-03 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.TextField(default='', verbose_name='所属电影')),
                ('content', models.TextField(default='', verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('author', models.CharField(default='', max_length=255, verbose_name='作者')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞数')),
                ('father', models.IntegerField(default=0, verbose_name='父评论ID')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
