# Generated by Django 2.0.6 on 2018-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuoJia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='国家/地区')),
                ('ename', models.CharField(default='', max_length=255, unique=True, verbose_name='国家/地区')),
            ],
            options={
                'verbose_name': '国家/地区',
                'verbose_name_plural': '国家/地区',
            },
        ),
        migrations.CreateModel(
            name='ShangYing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shijian', models.CharField(default='', max_length=255, verbose_name='时间')),
                ('guojia', models.CharField(default='', max_length=255, verbose_name='国家')),
                ('chengshi', models.CharField(default='', max_length=255, verbose_name='城市')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
            ],
            options={
                'verbose_name': '上映时间',
                'verbose_name_plural': '上映时间',
            },
        ),
        migrations.DeleteModel(
            name='Shanging',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
