# Generated by Django 2.0.5 on 2018-06-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180623_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='yanyuan',
            field=models.TextField(default='', max_length=255, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='info',
            name='chupingongsi',
            field=models.TextField(default='', max_length=255, verbose_name='出品公司'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zhipiangongsi',
            field=models.TextField(default='', max_length=255, verbose_name='制片公司'),
        ),
    ]
