# Generated by Django 2.0.5 on 2018-06-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180618_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='film.Info', verbose_name='获奖电影'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='person.Info', verbose_name='获奖者'),
        ),
    ]
