# Generated by Django 2.0.6 on 2018-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180625_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='YiMing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guojia', models.CharField(default='', max_length=255, unique=True, verbose_name='国家/地区')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='译名/别名')),
            ],
            options={
                'verbose_name': '译名/别名',
                'verbose_name_plural': '译名/别名',
            },
        ),
        migrations.RemoveField(
            model_name='info',
            name='yiming',
        ),
    ]
