# Generated by Django 2.0.5 on 2018-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20180618_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='result',
            field=models.CharField(choices=[(0, '获奖'), (1, '提名')], max_length=255, verbose_name='结果'),
        ),
    ]
