# Generated by Django 2.0.6 on 2018-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20180625_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='guojia',
            name='film',
            field=models.CharField(default='', max_length=255, verbose_name='所属电影'),
        ),
        migrations.AddField(
            model_name='yiming',
            name='film',
            field=models.CharField(default='', max_length=255, verbose_name='所属电影'),
        ),
    ]
