# Generated by Django 2.0.6 on 2018-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20180625_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='BianJi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '编辑人',
                'verbose_name_plural': '编辑人',
            },
        ),
        migrations.CreateModel(
            name='BianJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '编剧',
                'verbose_name_plural': '编剧',
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('juese', models.CharField(default='', max_length=255, verbose_name='挑选的角色')),
            ],
            options={
                'verbose_name': '角色挑选',
                'verbose_name_plural': '角色挑选',
            },
        ),
        migrations.CreateModel(
            name='DaoYan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '导演',
                'verbose_name_plural': '导演',
            },
        ),
        migrations.CreateModel(
            name='ShengChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '生产设计',
                'verbose_name_plural': '生产设计',
            },
        ),
        migrations.CreateModel(
            name='SheYing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '摄影人',
                'verbose_name_plural': '摄影人',
            },
        ),
        migrations.CreateModel(
            name='YinYue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '音乐人',
                'verbose_name_plural': '音乐人',
            },
        ),
        migrations.CreateModel(
            name='YiShu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '艺术指导',
                'verbose_name_plural': '艺术指导',
            },
        ),
        migrations.CreateModel(
            name='ZhiPian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='中文名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
            ],
            options={
                'verbose_name': '制片人',
                'verbose_name_plural': '制片人',
            },
        ),
        migrations.RemoveField(
            model_name='info',
            name='bianju',
        ),
        migrations.RemoveField(
            model_name='info',
            name='daoyan',
        ),
        migrations.RemoveField(
            model_name='info',
            name='yanyuan',
        ),
        migrations.AlterField(
            model_name='guojia',
            name='ename',
            field=models.CharField(default='', max_length=255, verbose_name='国家/地区(英文)'),
        ),
        migrations.AlterField(
            model_name='guojia',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='国家/地区(中文)'),
        ),
        migrations.AlterField(
            model_name='yiming',
            name='guojia',
            field=models.CharField(default='', max_length=255, verbose_name='国家/地区'),
        ),
        migrations.AlterField(
            model_name='yiming',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='译名/别名'),
        ),
    ]
