# Generated by Django 2.0.5 on 2018-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20180618_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='result',
            field=models.CharField(choices=[(1, '获奖'), (2, '提名')], max_length=255, verbose_name='结果'),
        ),
    ]
