# Generated by Django 2.0.5 on 2018-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20180618_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piaofang',
            name='num',
            field=models.IntegerField(verbose_name='收入'),
        ),
    ]
