# Generated by Django 2.0.5 on 2018-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_bujingshi_fuzhuang_huazhuang'),
    ]

    operations = [
        migrations.CreateModel(
            name='YanZhiYuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('name', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('ename', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('shenfen', models.CharField(default='', max_length=255, verbose_name='身份')),
                ('image', models.CharField(default='', max_length=255, verbose_name='头像')),
                ('beizhu', models.CharField(default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '演职人员',
                'verbose_name_plural': '演职人员',
            },
        ),
        migrations.DeleteModel(
            name='BianJi',
        ),
        migrations.DeleteModel(
            name='BianJu',
        ),
        migrations.DeleteModel(
            name='BuJingShi',
        ),
        migrations.DeleteModel(
            name='Casting',
        ),
        migrations.DeleteModel(
            name='DaoYan',
        ),
        migrations.DeleteModel(
            name='FuZhuang',
        ),
        migrations.DeleteModel(
            name='HuaZhuang',
        ),
        migrations.DeleteModel(
            name='ShengChan',
        ),
        migrations.DeleteModel(
            name='SheYing',
        ),
        migrations.DeleteModel(
            name='YinYue',
        ),
        migrations.DeleteModel(
            name='YiShu',
        ),
        migrations.DeleteModel(
            name='ZhiPian',
        ),
    ]
