# Generated by Django 2.0.5 on 2018-06-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20180625_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yanzhiyuan',
            name='shenfen',
        ),
        migrations.AddField(
            model_name='yanzhiyuan',
            name='category',
            field=models.CharField(choices=[('yy', '演员'), ('dy', '导演'), ('bj', '编剧'), ('zp', '制片人'), ('ms', '音乐'), ('sy', '摄影'), ('jj', '剪辑'), ('tx', '角色挑选'), ('zp', '制片设计'), ('hz', '化妆'), ('sc', '生产管理'), ('zl', '助理导演'), ('ms', '美术'), ('yx', '音效'), ('tx', '特效'), ('sj', '视觉'), ('tj', '特技'), ('dj', '道具场工'), ('dh', '动画'), ('dp', '底片冲印'), ('fz', '服装管理'), ('zb', '助理编辑'), ('cj', '场景管理'), ('md', '音乐部门'), ('ys', '底片运送'), ('qt', '其他职员')], default='', max_length=255, verbose_name='身份'),
        ),
    ]
