# Generated by Django 2.0.5 on 2018-06-18 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20180618_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='ejianjie',
            field=models.TextField(blank=True, null=True, verbose_name='英语简介'),
        ),
        migrations.AddField(
            model_name='info',
            name='ejuqing',
            field=models.TextField(blank=True, null=True, verbose_name='英语剧情'),
        ),
        migrations.AlterField(
            model_name='info',
            name='add_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='收录时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bianju',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='编剧'),
        ),
        migrations.AlterField(
            model_name='info',
            name='chengben',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='制片成本'),
        ),
        migrations.AlterField(
            model_name='info',
            name='chupingongsi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出品公司'),
        ),
        migrations.AlterField(
            model_name='info',
            name='daoyan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='info',
            name='duibai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='对白语言'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='imdb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IMDB编码'),
        ),
        migrations.AlterField(
            model_name='info',
            name='jianjie',
            field=models.TextField(blank=True, null=True, verbose_name='汉语简介'),
        ),
        migrations.AlterField(
            model_name='info',
            name='juqing',
            field=models.TextField(blank=True, null=True, verbose_name='汉语剧情'),
        ),
        migrations.AlterField(
            model_name='info',
            name='misuc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='电影原声'),
        ),
        migrations.AlterField(
            model_name='info',
            name='paishedi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拍摄地点'),
        ),
        migrations.AlterField(
            model_name='info',
            name='paisheriqi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拍摄日期'),
        ),
        migrations.AlterField(
            model_name='info',
            name='secai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='色彩'),
        ),
        migrations.AlterField(
            model_name='info',
            name='shangying',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='上映时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='shichang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='info',
            name='yanyuan',
            field=models.ManyToManyField(blank=True, null=True, to='person.Info', verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='info',
            name='yiming',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='译名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zhipiandiqu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='制片地区'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zhipiangongsi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='制片公司'),
        ),
        migrations.AlterField(
            model_name='role',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='角色描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='fengmian',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='角色封面'),
        ),
    ]
