# Generated by Django 2.0.5 on 2018-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20180618_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='aiqiyi',
            field=models.TextField(blank=True, null=True, verbose_name='爱奇艺'),
        ),
        migrations.AddField(
            model_name='info',
            name='bilibili',
            field=models.TextField(blank=True, null=True, verbose_name='bilibili地址'),
        ),
        migrations.AddField(
            model_name='info',
            name='db_fen',
            field=models.IntegerField(blank=True, null=True, verbose_name='豆瓣评分'),
        ),
        migrations.AddField(
            model_name='info',
            name='imdb_fen',
            field=models.IntegerField(blank=True, null=True, verbose_name='豆瓣评分'),
        ),
        migrations.AddField(
            model_name='info',
            name='youku',
            field=models.TextField(blank=True, null=True, verbose_name='优酷地址'),
        ),
    ]
