# Generated by Django 2.0.5 on 2018-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20180618_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='电影名'),
        ),
    ]
