# Generated by Django 2.0.5 on 2018-06-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_auto_20180619_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhaiYao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='摘要内容')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='film.Info', verbose_name='所属电影')),
            ],
            options={
                'verbose_name': '摘要',
                'verbose_name_plural': '摘要',
            },
        ),
    ]
