# Generated by Django 2.0.5 on 2018-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_chuanbang'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuanbang',
            name='category',
            field=models.CharField(default='', max_length=255, verbose_name='穿帮类型'),
        ),
    ]
