# Generated by Django 2.0.5 on 2018-06-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_zhaiyao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='film.Category', verbose_name='类型'),
        ),
    ]
