# Generated by Django 2.0.5 on 2018-06-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_auto_20180622_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shanging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shijian', models.CharField(max_length=255, verbose_name='时间')),
            ],
            options={
                'verbose_name': '上映时间',
                'verbose_name_plural': '上映时间',
            },
        ),
        migrations.RemoveField(
            model_name='info',
            name='shangying',
        ),
        migrations.AddField(
            model_name='info',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='年代'),
        ),
        migrations.AddField(
            model_name='shanging',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='film.Info', verbose_name='所属电影'),
        ),
    ]
