# Generated by Django 2.0.5 on 2018-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_chuanbang_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuaXu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('huaxu', models.CharField(default='', max_length=255, verbose_name='花絮')),
            ],
            options={
                'verbose_name': '花絮',
                'verbose_name_plural': '花絮',
            },
        ),
    ]
