# Generated by Django 2.0.5 on 2018-06-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_auto_20180622_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='jibie',
            field=models.TextField(blank=True, null=True, verbose_name='电影级别'),
        ),
        migrations.AlterField(
            model_name='info',
            name='imdb_fen',
            field=models.IntegerField(blank=True, null=True, verbose_name='IMDB评分'),
        ),
    ]
