# Generated by Django 2.0.5 on 2018-06-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_auto_20180622_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='类型'),
        ),
    ]
