# Generated by Django 2.0.5 on 2018-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_jishu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GongSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(default='', max_length=255, verbose_name='所属电影')),
                ('category', models.CharField(default='', max_length=255, verbose_name='类型')),
                ('name', models.TextField(default='', max_length=255, verbose_name='公司名')),
                ('desc', models.TextField(default='', max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '支持公司',
                'verbose_name_plural': '支持公司',
            },
        ),
    ]
