# Generated by Django 2.0.5 on 2018-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0017_gongsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gongsi',
            name='desc',
        ),
        migrations.AlterField(
            model_name='gongsi',
            name='name',
            field=models.TextField(default='', max_length=255, verbose_name='公司名及描述'),
        ),
    ]
